[platformio]
default_envs = perso_esp32

[env:perso_esp32]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  https://github.com/Seeed-Studio/PN532.git#2c47f5c836af53158c4e29685551612181fd8f9b
lib_ignore =
  NDEF
build_flags =
  -D NFC_INTERFACE_I2C=1
  -Wall
  -Wextra

[env:perso_esp32_spi]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  https://github.com/Seeed-Studio/PN532.git#2c47f5c836af53158c4e29685551612181fd8f9b
lib_ignore =
  NDEF
build_flags =
  -D NFC_INTERFACE_SPI=1
  -D PERSO_NFC_SPI=1
  -Wall
  -Wextra
