CREATE TABLE IF NOT EXISTS operators (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  pin_salt VARBINARY(32) NOT NULL,
  pin_hash VARBINARY(64) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  card_token VARCHAR(64) NOT NULL UNIQUE,
  full_name VARCHAR(160) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  request_id CHAR(36) NOT NULL UNIQUE,
  card_token VARCHAR(64) NOT NULL,
  operator_id BIGINT UNSIGNED NOT NULL,
  action VARCHAR(32) NOT NULL,
  amount_liter SMALLINT NULL,
  balance_before SMALLINT NULL,
  balance_after SMALLINT NULL,
  outcome VARCHAR(24) NOT NULL,
  detail VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_transactions_card_time (card_token, created_at),
  CONSTRAINT fk_transactions_operator FOREIGN KEY (operator_id) REFERENCES operators(id)
);
CREATE TABLE IF NOT EXISTS card_wallet_state (
  card_token VARCHAR(64) PRIMARY KEY,
  balance SMALLINT NOT NULL,
  active TINYINT(1) NOT NULL,
  schedule TINYINT UNSIGNED NOT NULL DEFAULT 0,
  used_today SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  reserved SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  revision INT UNSIGNED NOT NULL DEFAULT 0,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_wallet_state_active_schedule (active, schedule)
);
CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  operator_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(48) NOT NULL,
  card_token VARCHAR(64) NULL,
  detail VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_time (created_at)
);
CREATE TABLE IF NOT EXISTS app_config (
  config_key VARCHAR(64) PRIMARY KEY,
  config_value VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
